"""Generate a complete Eigenflow development-instrumentation demonstration bundle."""
from __future__ import annotations
from pathlib import Path
import csv,hashlib,json,platform,shutil,subprocess,sys
import eigenflow

ROOT=Path.cwd()/"eigenflow_development_demo_outputs"
if ROOT.exists(): shutil.rmtree(ROOT)
ROOT.mkdir()

scripts=["architecture_comparison.py","fine_tuning_checkpoints.py"]
examples_dir=Path(__file__).resolve().parent
for script in scripts:
    run_dir=ROOT/Path(script).stem; run_dir.mkdir()
    proc=subprocess.run([sys.executable,str(examples_dir/script)],cwd=run_dir,text=True,capture_output=True,check=True)
    (run_dir/"console.log").write_text(proc.stdout+proc.stderr)

metadata={
    "eigenflow_version":eigenflow.__version__,
    "python":sys.version,
    "platform":platform.platform(),
    "examples":scripts,
    "purpose":"Architecture comparison plus longitudinal fine-tuning/retention demonstration",
    "interpretation_boundary":"Structural changes are hypothesis-conditioned measurements, not a universal model-quality score.",
}
(ROOT/"metadata.json").write_text(json.dumps(metadata,indent=2))

manifest=[]
for f in sorted(ROOT.rglob("*")):
    if f.is_file() and f.name!="SHA256SUMS.csv":
        rel=f.relative_to(ROOT).as_posix(); digest=hashlib.sha256(f.read_bytes()).hexdigest()
        manifest.append({"path":rel,"sha256":digest,"bytes":f.stat().st_size})
with (ROOT/"SHA256SUMS.csv").open("w",newline="") as fp:
    w=csv.DictWriter(fp,fieldnames=["path","sha256","bytes"]); w.writeheader(); w.writerows(manifest)

readme="""# Eigenflow development instrumentation demonstration\n\nThis bundle is generated by `examples/complete_development_demo.py`. It contains a matched architecture-comparison experiment and a genuine longitudinal fine-tuning experiment with target acquisition and retention loss.\n\nThe architecture directory contains the compatibility report, development report, persisted `ExperimentSeries`, console log, and comparison figure. The fine-tuning directory contains the versioned probe-suite manifest, target/retention persisted checkpoint series, retention summary, PEFT-targeting diagnostic scores, console log, and longitudinal figures.\n\nThe numerical results are specific to the deterministic synthetic examples. They demonstrate the API and inferential workflow; they are not universal thresholds or benchmark claims.\n"""
(ROOT/"README.md").write_text(readme)
zip_path=Path.cwd()/"eigenflow_development_demo_outputs.zip"
if zip_path.exists(): zip_path.unlink()
shutil.make_archive(str(zip_path.with_suffix("")),"zip",ROOT)
print(zip_path)
